baseURL = "https://kms9.github.io"
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true

# 网站标题
title = "记录流水账"
theme = "LoveIt"

defaultLayout = "posts"

[params]
  version = "0.1.X"
  
[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    name = "所有文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    name = "关于我"
    url = "/about/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "about-blog"
    pre = ""
    name = "关于本记录"
    url = "/about-blog/"
    title = ""
    weight = 5
    
tags = [
  "blog",
  "clean",
  "responsive",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized"
]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  